# Generated by Django 4.1.2 on 2022-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=100)),
                ('longDescription', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
