# Generated by Django 4.1.2 on 2022-10-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('toDo', 'Todo'), ('inProgress', 'Inprogress'), ('done', 'Done')], max_length=10),
        ),
    ]
