# Generated by Django 4.1.2 on 2022-11-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='state',
            field=models.CharField(blank=True, choices=[('toDo', 'Todo'), ('inProgress', 'Inprogress'), ('done', 'Done')], max_length=10),
        ),
    ]
