# Generated by Django 4.1.2 on 2022-11-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_file_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='state',
        ),
    ]
