# Generated by Django 4.1.2 on 2022-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_file_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='longDescription',
        ),
        migrations.RemoveField(
            model_name='task',
            name='shortDescription',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
