# Generated by Django 4.1.2 on 2022-11-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_longdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='projectName',
            new_name='projectId',
        ),
    ]
