# Generated by Django 4.1.2 on 2022-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projectId',
            field=models.IntegerField(editable=False),
        ),
    ]
