# Generated by Django 4.1.2 on 2022-11-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_task_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projectName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
    ]
