# Generated by Django 4.1.2 on 2022-11-16 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
