# Generated by Django 4.1.2 on 2022-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_remove_task_creationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
